//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app_console
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public Employees()
        {
            this.Attendance = new HashSet<Attendance>();
            this.LeaveRequest = new HashSet<LeaveRequest>();
            this.Salaries = new HashSet<Salaries>();
            this.Schedules = new HashSet<Schedules>();
        }
    
        public int EmployeeID { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Position { get; set; }
        public System.DateTime HireDate { get; set; }
    
        public virtual ICollection<Attendance> Attendance { get; set; }
        public virtual ICollection<LeaveRequest> LeaveRequest { get; set; }
        public virtual ICollection<Salaries> Salaries { get; set; }
        public virtual ICollection<Schedules> Schedules { get; set; }


        public string RenderGender(bool? gender)
        {
            if ((bool)gender)
            {
                return "Nu";
            }
            return "Nam";
        }

        public void Export() => Console.WriteLine($"Id: {this.EmployeeID} | Full Name: {this.FullName} | Phone: {this.Phone} | Email: {this.Email} | Address: {this.Address} | Gender: {RenderGender(this.Gender)}");
    }
}
