//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app_console
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManageStaffEntities : DbContext
    {
        public ManageStaffEntities()
            : base("name=ManageStaffEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Attendance> Attendance { get; set; }
        public DbSet<Employees> Employees { get; set; }
        public DbSet<LeaveRequest> LeaveRequest { get; set; }
        public DbSet<Salaries> Salaries { get; set; }
        public DbSet<Schedules> Schedules { get; set; }
        public DbSet<Shifts> Shifts { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
