//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app_console
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salaries
    {
        public int SalaryID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime MonthYear { get; set; }
        public decimal TotalWorkHours { get; set; }
        public decimal HourlyWage { get; set; }
        public Nullable<decimal> TotalSalary { get; set; }
        public Nullable<decimal> Bonus { get; set; }
        public Nullable<decimal> Deductions { get; set; }
        public Nullable<decimal> FinalSalary { get; set; }
        public Nullable<decimal> Allowance { get; set; }
        public Nullable<double> OverTimeRate { get; set; }
        public Nullable<int> TotalOvertimeHours { get; set; }
        public Nullable<decimal> OverTimeSalary { get; set; }
        public Nullable<decimal> BaseSalary { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
