//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app_console
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shifts
    {
        public Shifts()
        {
            this.Attendance = new HashSet<Attendance>();
            this.Schedules = new HashSet<Schedules>();
        }
    
        public int ShiftID { get; set; }
        public string ShiftName { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
    
        public virtual ICollection<Attendance> Attendance { get; set; }
        public virtual ICollection<Schedules> Schedules { get; set; }

        public void Export() => Console.WriteLine($"ShiftId: {this.ShiftID} | ShiftName: {this.ShiftName} | StartTime: {this.StartTime} | EndTime: {this.EndTime}");
    }
}
